echo on
\HeadFirstDesignPatterns\c_plusplus\Silver\Adapter\Ducks\Debug\Ducks.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Adapter\Ducks\Release\Ducks.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Bridge\Remotes\Debug\Remotes.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Bridge\Remotes\Release\Remotes.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Builder\Planner\Debug\Planner.exe < .\vacation.txt
\HeadFirstDesignPatterns\c_plusplus\Silver\Builder\Planner\Release\Planner.exe < .\vacation.txt
\HeadFirstDesignPatterns\c_plusplus\Silver\ChainOfResponsibility\GumballEMailHandler\debug\GumballEMailHandler.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\ChainOfResponsibility\GumballEMailHandler\release\GumballEMailHandler.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Command\Remote\Debug\Remote.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Command\Remote\Release\Remote.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Command\SimpleRemote\Debug\SimpleRemote.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Command\SimpleRemote\Release\SimpleRemote.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Command\Undo\Debug\Undo.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Command\Undo\Release\Undo.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Composite\Menus\Debug\Menus.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Composite\Menus\Release\Menus.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Adapter\DuckSimulator\Debug\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Adapter\DuckSimulator\Release\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Composite\DuckSimulator\Debug\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Composite\DuckSimulator\Release\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Decorator\DuckSimulator\Debug\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Decorator\DuckSimulator\Release\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Ducks\DuckSimulator\Debug\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Ducks\DuckSimulator\Release\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Factory\DuckSimulator\Debug\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Factory\DuckSimulator\Release\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Observer\DuckSimulator\Debug\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Compound\Observer\DuckSimulator\Release\DuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Decorator\Debug\Starbuzz.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Decorator\Release\Starbuzz.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Factory\Pizzas\Debug\Pizzas.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Factory\Pizzas\Release\Pizzas.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Factory\Pizzafm\Debug\Pizzafm.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Factory\Pizzafm\Release\Pizzafm.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Factory\Pizzaaf\Debug\Pizzaaf.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Factory\Pizzaaf\Release\Pizzaaf.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Facade\HomeTheater\Debug\HomeTheater.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Facade\HomeTheater\Release\HomeTheater.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Flyweight\FowlWeight\Debug\FowlWeight.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Flyweight\Fowlweight\Release\FowlWeight.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Iterator\DinerMerger\Debug\DinerMerger.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Iterator\DinerMerger\Release\DinerMerger.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Iterator\DinerMergerI\Debug\DinerMergerI.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Iterator\DinerMergerI\Release\DinerMergerI.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Observer\Debug\WeatherStation.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Observer\Release\WeatherStation.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Singleton\Chocolate\Debug\Chocolate.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Singleton\Chocolate\Release\Chocolate.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\State\GumballStateWinner\Debug\GumballStateWinner.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\State\GumballStateWinner\Release\GumballStateWinner.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Strategy\Debug\MiniDuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Strategy\Release\MiniDuckSimulator.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Template\Barista\Debug\Barista.exe
\HeadFirstDesignPatterns\c_plusplus\Silver\Template\Barista\Release\Barista.exe